---
- hosts: tomcat
  become: true
  roles:
  - install_pre
- hosts: tomcat
  become: true
  become_user: tomcat
  roles:
  - install_tomcat
- hosts: tomcat
  become: true
  roles:
  - install_post
